basePath: /
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.ProductResponse:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      vat:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис для управления товарами в кофейне.
  title: Coffee Shop API
  version: "1.0"
paths:
  /api/products/:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ProductResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
  /api/products/{id}:
    get:
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
swagger: "2.0"
